name: 'logging-monitoring-elk'

services:
  elasticsearch-rs:
    image: elasticsearch:8.0.0
    container_name: elasticsearch-rs
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      elk-network:

  kibana-rs:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana-rs
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana-server-rs
      ELASTICSEARCH_URL: http://elasticsearch-rs:9200"
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-rs:9200"]'
      ELASTICSEARCH_USERNAME: "kusername"
      ELASTICSEARCH_PASSWORD: "kpassword"
    depends_on:
      - elasticsearch-rs
    networks:
      elk-network:

  logstash-rs:
    image: logstash:8.0.0
    container_name: logstash-rs
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    networks:
      elk-network:
    depends_on:
      - elasticsearch-rs

networks:
  elk-network:
    driver: bridge

