name: "Infrastructure"

services:
  recipe-share-db:
    image: postgres:16-alpine
    container_name: recipe-share-db
    environment:
      - PGUSER=recipe_user                # SETS USERNAME FOR DEFAULT PSQL CONNECTION
      - PGDATABASE=recipe_db              # SETS DATABASE FOR DEFAULT PSQL CONNECTION
      - POSTGRES_DB=recipe_db             # CREATES A TABLE
      - POSTGRES_USER=recipe_user         # CREATES THE DEFAULT USER
      - POSTGRES_PASSWORD=recipe_secret   # APPLIES PASSWORD TO THE DEFAULT USER
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c pg_isready -U ${POSTGRES_USER} -d" ]
      interval: "10s"
      timeout: "3s"
      retries: 5