version: '3'

tasks:
  start-infra:
    cmd: "docker compose -f deployment/compose/infra.yml up -d"

  stop-infra:
    cmd: "docker compose -f deployment/compose/infra.yml down"

  restart-infra:
    cmds:
      - task: stop-infra
      - "timeout 2"
      - task: start-infra

  start-elk:
    cmd: "docker compose -f deployment/compose/elk.yml up -d"

  stop-elk:
    cmd: "docker compose -f deployment/compose/elk.yml down"

  restart-elk:
    cmds:
      - task: stop-elk
      - "timeout 2"
      - task: start-elk